### ISSUE TITLE
got error building the firmware

### ISSUE THREAD

**Issue by 256ericpan** [Seeed-Studio/SenseCAP-Watcher-Firmware#63]
idf.py build
Executing action: all (aliases: build)
Running cmake in directory C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DPYTHON=C:\Users\ericp\.espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware"...
-- Found Git: C:/Users/ericp/.espressif/tools/idf-git/2.39.2/cmd/git.exe (found version "2.39.2.windows.1")
-- ccache will be used for faster recompilation
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: C:/Users/ericp/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/ericp/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/ericp/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
Cannot parse the manifest file. Please check that
        C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware\main\idf_component.yml
is a valid YAML file

CMake Error at C:/Users/ericp/esp/v5.1.2/esp-idf/tools/cmake/build.cmake:540 (message):
  ERROR: Manifest is not valid

Call Stack (most recent call first):
  C:/Users/ericp/esp/v5.1.2/esp-idf/tools/cmake/project.cmake:547 (idf_build_process) 
  CMakeLists.txt:14 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Work/reCare/SenseCAP-Watcher/examples/factory_firmware/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1, output of the command is in the C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware\build\log\idf_py_stderr_output_26432 and C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware\build\log\idf_py_stdout_output_26432  
PS C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware> idf.py build
Executing action: all (aliases: build)
Running cmake in directory C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware\build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DPYTHON=C:\Users\ericp\.espressif\python_env\idf5.1_py3.11_env\Scripts\python.exe -DESP_PLATFORM=1 -DCCACHE_ENABLE=1 C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware"...
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/ericp/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/ericp/.espressif/tools/xtensa-esp32-elf/es-- Detecting C compiler ABI info - done
p-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe - skipped
-- Detecting C compile features
p-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Users/ericp/.espressif/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
Cannot parse the manifest file. Please check that
        C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware\main\idf_component.yml
is a valid YAML file

CMake Error at C:/Users/ericp/esp/v5.1.2/esp-idf/tools/cmake/build.cmake:540 (message):
  ERROR: Manifest is not valid

Call Stack (most recent call first):
  C:/Users/ericp/esp/v5.1.2/esp-idf/tools/cmake/project.cmake:547 (idf_build_process)
  CMakeLists.txt:14 (project)

-- Configuring incomplete, errors occurred!
See also "C:/Work/reCare/SenseCAP-Watcher/examples/factory_firmware/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1, output of the command is in the C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware\build\log\idf_py_stderr_output_17464 and C:\Work\reCare\SenseCAP-Watcher\examples\factory_firmware\build\log\idf_py_stdout_output_17464

**Comment by Lesords** [comment]
@Wvirgil123 @QingWind6 Help with this one.

**Comment by Wvirgil123** [comment]
The log message indicates that the file (SenseCAP-Watcher\examples\factory_firmware\main\idf_component.yml) is invalid. Check if the file has been modified.

**Comment by Wvirgil123** [comment]
It is recommended to use idf v5.2.1 version to compile.

**Comment by 256ericpan** [comment]
Oh, didn't notice I have to use the specific version for the xample. it works now, thank you!

**Comment by Lesords** [comment]
Hello,

I'm going to close this issue, feel free to re-open it if you have any other questions.
